# Numpy--Python开源的科学计算工具包
高级的数值编程工具
* 强大的N纬数组对象：ndarray
* 对数据结构数据进行计算（不用遍历循环）
* 随机数、线性代数、傅立叶变换

## 基础数据结构

In [3]:
import numpy as np

In [7]:
ar = np.array([1, 2, 3, 4, 5, 6]) # 创建一个一维数组
print(ar, type(ar))
print(ar.ndim) # 显示维度
print(ar.shape) # 先行后列
print(ar.size) # 总共元素个数
print(ar.dtype) # 数组内数据的类型
print(ar.itemsize) # 每个字节的大小
print(ar.data) # 显示元素内所有数据的缓存区

(6,)
6
int64
8


### 创建数组
#### array()，可以是list/tuple/array/generator

In [11]:
ar1 = np.array(range(10)) # python内置range
print(ar1)
ar2 = np.arange(10) # numpy内置arange，主要用法
print(ar2)
ar3 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]) # list
print(ar3)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]
 [2 3 4 5 6]]


#### linspace()，返回在间隔[开始，停止]上计算的num个均匀间隔样本  
默认前闭后闭。endpoint==False，则为前闭后开;  
默认不显示步长。retstep==True，显示步长

In [13]:
print(np.linspace(10, 20, num=20, endpoint=False))

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5]


In [21]:
print(np.zeros((3, 5), dtype=np.int), '\n') # 直接创建为零的array
print(np.zeros_like(ar3), '\n') # 创建类似于ar3的零array
print(np.ones((3, 5)), '\n') # 创建一个均为1的array
print(np.ones_like(ar3), '\n') # 创建类似于ar3的全为1array
print(np.eye(5)) # 创建一个5*5的单位矩阵

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 

[[0 0 0 0 0]
 [0 0 0 0 0]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[1 1 1 1 1]
 [1 1 1 1 1]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 通用函数

### 数组形状
* .T 转置
* .reshape()  更改形状
* .resize()  同reshape区分。修改大小，如果原数组大小不匹配，自动增减

In [31]:
ar1 = np.zeros((2, 5))
print(ar1)
print(ar1.T)
print(ar1.reshape(5, 2))
print(np.resize(ar1, (3, 5))) # 修改为3，5的大小

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 数组的复制
* 直接等号赋值，实际仍然指向原数组
* .copy()复制出一个新数组

In [36]:
ar1 = np.arange(10)
ar2 = ar1
print('ar2=ar1,', ar2 is ar1)
ar1[2] = 100
print(ar1, ar2) # 等号赋值，二者指向一个数组
#########################
ar3 = ar1.copy()
ar1[3] = 100
print(ar1, ar3) # copy()复制一个新数组

ar2=ar1, True
[  0   1 100   3   4   5   6   7   8   9] [  0   1 100   3   4   5   6   7   8   9]
[  0   1 100 100   4   5   6   7   8   9] [  0   1 100   3   4   5   6   7   8   9]


In [39]:
# resize的使用
s = np.arange(10)
print(s, '\n')
print(np.resize(s, (2, 6))) # 生成一个新数组
print(s, '\n')
print(s.resize(2, 6)) # 没有生成一个新数组，在原数组基础上进行操作
print(s, '\n')

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4 5]
 [6 7 8 9 0 1]]
[0 1 2 3 4 5 6 7 8 9] 

None
[[0 1 2 3 4 5]
 [6 7 8 9 0 0]] 



### 数组类型转换 
.astype()

In [40]:
ar1 = np.arange(10, dtype=float)
ar2 = ar1.astype(np.int64)
print(ar1, ar1.dtype)
print(ar2, ar2.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
[0 1 2 3 4 5 6 7 8 9] int64


### 数组堆叠
* hstack() 横向连接
* vstack() 纵向连接
* stack() 连接，默认axis=0纵向连接，axis=1横向连接

In [51]:
# 横向连接
a = np.arange(5)
b = np.arange(5, 10)
print(a, b, '\n')
print(np.hstack((a, b)))
print('-----------')

# 纵向连接
a = np.array([[1], [2], [3]])
b = np.array([['a'], ['b'], ['c']])
print(a, b, '\n')
print(np.vstack((a, b)))
print('-----------')

# stack
a = np.arange(5)
b = np.arange(5, 10)
print(np.stack((a, b), axis=0))
print(np.stack((a, b), axis=1))

[0 1 2 3 4] [5 6 7 8 9] 

[0 1 2 3 4 5 6 7 8 9]
-----------
[[1]
 [2]
 [3]] [['a']
 ['b']
 ['c']] 

[['1']
 ['2']
 ['3']
 ['a']
 ['b']
 ['c']]
-----------
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### 数组拆分
* hsplit()
* vsplit()

In [55]:
ar = np.arange(16).reshape(4, 4)
print(ar, '\n')
print(np.hsplit(ar, 2), '\n')
print(np.vsplit(ar, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])] 

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


## 索引及切片

### 基本索引及切片

In [56]:
# 一维数组类似于list
ar = np.arange(20)
print(ar)
print(ar[4])
print(ar[:3])
print('----------')

# 二维数组类似于list的list
ar = np.arange(16).reshape(4, 4)
print(ar)
print(ar[2])
print(ar[2][2])
print(ar[2, 2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
4
[0 1 2]
----------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 8  9 10 11]
10
10


### 布尔型索引及切片

In [59]:
ar = np.arange(12).reshape(3, 4)
print(ar)
i = np.array([True, False, True]) 
j = np.array([True, True, False, False])
print(ar[i, :]) # 在第一纬度做判断
print(ar[:, j]) # 在第二纬度做判断
print('---------\n')

print(ar>5)
print(ar[ar>5])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
---------

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11]


### 数组索引及切片的值更改/复制
当一个常数赋值给一个索引/切片时，会自动改变/传播原始数组

In [60]:
ar = np.arange(10)
print(ar)
ar[5] = 100
ar[7:9] = 200
print(ar)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4 100   6 200 200   9]


## 随机数
numpy.random包含多种概率分布的随机样本

In [62]:
# 标准正态分布
print(np.random.normal(size=(4, 4)), '\n')

[[ 0.35132353 -1.41989721  0.00915843  0.33247811]
 [-0.37998641  0.40741483  0.2289659  -1.60274079]
 [ 0.59111889  1.34554307 -0.39165622  0.04355201]
 [ 0.70350161  1.73428028 -0.4680661  -0.60484237]] 



In [65]:
# 生成[0, 1)之间的随机浮点数或N纬浮点数组————均匀分布
print(np.random.rand())
print(np.random.rand(2, 4))

# 生成[0, 1)之间的随机浮点数或N纬浮点数组————正态分布
print(np.random.randn())
print(np.random.randn(2, 4))

0.4804052765041311
[[0.61635228 0.79209186 0.04450497 0.28735703]
 [0.87521979 0.06705252 0.47565617 0.07034965]]
-0.9851254958102285
[[ 0.83869221  0.71138141  0.94021231 -0.3420251 ]
 [-0.33028745  0.63314498 -0.88768385  0.99400949]]


In [70]:
# 生成一个一定范围内的随机整数
# random.randint(low, high=None, size=None, dtype='') 
# 如果high非None，取[low, high)之间的随机整数；
# 如果high为None，取[0, low)之间的随机整数
# size为生成多少个随机整数

print(np.random.randint(2))
print(np.random.randint(2, 10))
print(np.random.randint(2, size=10))
print(np.random.randint(10, 50, size=(2, 5)))

0
7
[0 1 0 1 1 1 0 1 0 0]
[[44 27 26 48 17]
 [41 18 33 40 19]]


## 数据的输入输出

### 存储数组数据

In [74]:
ar = np.random.rand(5, 5)
print(ar)
np.save('arraydata.npy', ar)
np.savetxt('arraydata.txt', ar, delimiter=',') # 以txt格式存储

[[0.97239789 0.03795755 0.12872722 0.25799825 0.07974997]
 [0.94437366 0.77667278 0.96777752 0.74123936 0.15916592]
 [0.08595364 0.44203063 0.6055497  0.42409651 0.48416684]
 [0.11723357 0.68578136 0.73415801 0.24982079 0.00714795]
 [0.41904401 0.25181826 0.38589261 0.33213207 0.42189269]]


### 读取数组数据

In [75]:
ar_load = np.load('arraydata.npy')
print(ar_load)
ar_loadtxt = np.loadtxt('arraydata.txt', delimiter=',') # 读取txt
print(ar_loadtxt)

[[0.97239789 0.03795755 0.12872722 0.25799825 0.07974997]
 [0.94437366 0.77667278 0.96777752 0.74123936 0.15916592]
 [0.08595364 0.44203063 0.6055497  0.42409651 0.48416684]
 [0.11723357 0.68578136 0.73415801 0.24982079 0.00714795]
 [0.41904401 0.25181826 0.38589261 0.33213207 0.42189269]]
[[0.97239789 0.03795755 0.12872722 0.25799825 0.07974997]
 [0.94437366 0.77667278 0.96777752 0.74123936 0.15916592]
 [0.08595364 0.44203063 0.6055497  0.42409651 0.48416684]
 [0.11723357 0.68578136 0.73415801 0.24982079 0.00714795]
 [0.41904401 0.25181826 0.38589261 0.33213207 0.42189269]]
